/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DadosAluno;
import dao.DadosEmpresa;
import dao.DadosEquipe;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Empresa;
import model.Equipe;
import model.EstadoAluno;


/**
 *
 * @author Ygor
 */
public class GuiAssociarColaborador extends javax.swing.JInternalFrame {
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    private static boolean aberto = false;
    private boolean consultando = true;
    
    private Empresa empresa;
    private Equipe equipe;
    private Aluno aluno;

    private final DadosAluno dadosAluno = new DadosAluno();
    private final DadosEmpresa dadosEmpresa = new DadosEmpresa();
    private final DadosEquipe dadosEquipe = new DadosEquipe();
    
    private List<Empresa> empresas = new ArrayList<>();
    private List<Equipe> equipes = new ArrayList<>();
    private List<Aluno> alunos = new ArrayList<>();
    
    private static final String cboInicialFiltrar = "Filtrar:";
    private static final String cboInicialSelecionar = "Selecione:";
    
    private Integer totalNaoMatriculados = 0;
    private Integer totalMatriculados = 0;
    
    /**
     * Creates new form GuiTurma
     */
    public GuiAssociarColaborador() {
        initComponents();
    }
    
    public static GuiAssociarColaborador getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiAssociarColaborador();
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAluno = new javax.swing.JPanel();
        lblEquipe = new javax.swing.JLabel();
        btnAssociarTodos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNaoMatriculados = new javax.swing.JList<>();
        btnAssociarUm = new javax.swing.JButton();
        btnDesassociarTodos = new javax.swing.JButton();
        btnDesassociarUm = new javax.swing.JButton();
        lblEquipeSelecionada = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        lblTotalNaoMatriculados = new javax.swing.JLabel();
        lblTotalMatriculados = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstMatriculados = new javax.swing.JList<>();
        pnlDados1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        cboEmpresa = new javax.swing.JComboBox<>();
        lblEmpresaAluno = new javax.swing.JLabel();
        cboEquipe = new javax.swing.JComboBox<>();
        lblTimeAluno = new javax.swing.JLabel();
        chbTodasEmpresas = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Matricular Aluno");

        pnlAluno.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlAlunoComponentShown(evt);
            }
        });

        lblEquipe.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblEquipe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEquipe.setText("Matriculados:");

        btnAssociarTodos.setText(">>");
        btnAssociarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarTodosActionPerformed(evt);
            }
        });

        lstNaoMatriculados.setModel(new DefaultListModel());
        lstNaoMatriculados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstNaoMatriculados);

        btnAssociarUm.setText(">");
        btnAssociarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarUmActionPerformed(evt);
            }
        });

        btnDesassociarTodos.setText("<<");
        btnDesassociarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesassociarTodosActionPerformed(evt);
            }
        });

        btnDesassociarUm.setText("<");
        btnDesassociarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesassociarUmActionPerformed(evt);
            }
        });

        lblEquipeSelecionada.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEquipeSelecionada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipeSelecionada.setText("[equipe]");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Não Matriculados:");

        jLabel3.setText("Total:");

        jLabel5.setText("Total:");

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lblTotalNaoMatriculados.setText("[total]");

        lblTotalMatriculados.setText("[total]");

        lstMatriculados.setModel(new DefaultListModel());
        lstMatriculados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(lstMatriculados);

        javax.swing.GroupLayout pnlAlunoLayout = new javax.swing.GroupLayout(pnlAluno);
        pnlAluno.setLayout(pnlAlunoLayout);
        pnlAlunoLayout.setHorizontalGroup(
            pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlunoLayout.createSequentialGroup()
                .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDesassociarUm, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDesassociarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssociarUm, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssociarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalNaoMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addComponent(lblEquipe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlunoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblEquipeSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAlunoLayout.setVerticalGroup(
            pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipeSelecionada)
                            .addComponent(lblEquipe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAlunoLayout.createSequentialGroup()
                                .addComponent(btnAssociarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAssociarUm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlunoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlunoLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnDesassociarUm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDesassociarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(lblTotalNaoMatriculados)
                                .addComponent(lblTotalMatriculados)))
                        .addGap(40, 40, 40))
                    .addGroup(pnlAlunoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlDados1.setBackground(new java.awt.Color(220, 220, 220));
        pnlDados1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        cboEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEmpresaItemStateChanged(evt);
            }
        });

        lblEmpresaAluno.setText("Empresa:");

        cboEquipe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEquipeItemStateChanged(evt);
            }
        });

        lblTimeAluno.setText("Equipe:");

        chbTodasEmpresas.setText("Exibir todos os alunos");
        chbTodasEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTodasEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDados1Layout = new javax.swing.GroupLayout(pnlDados1);
        pnlDados1.setLayout(pnlDados1Layout);
        pnlDados1Layout.setHorizontalGroup(
            pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpresaAluno)
                    .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimeAluno)
                    .addGroup(pnlDados1Layout.createSequentialGroup()
                        .addComponent(cboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbTodasEmpresas)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlDados1Layout.setVerticalGroup(
            pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDados1Layout.createSequentialGroup()
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDados1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDados1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmpresaAluno)
                                .addComponent(lblTimeAluno))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDados1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbTodasEmpresas))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pnlAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        resetarTela();
        preencherCboEmpresa();
        preencherCboEquipe(empresa);
        //atualizarTotalizadores();
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void cboEquipeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEquipeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEquipeItemStateChanged

    private void cboEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEmpresaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED && cboEmpresa.getSelectedItem()!=cboInicialFiltrar) { // Restringe execução apenas em caso de seleção manual no combobox
            Empresa emp = (Empresa) cboEmpresa.getSelectedItem();
            preencherCboEquipe(emp);

        }
        
        if (cboEmpresa.getSelectedItem().equals(cboInicialFiltrar)) {
            cboEquipe.removeAllItems();
            cboEquipe.addItem(cboInicialSelecionar);
        }
   
    }//GEN-LAST:event_cboEmpresaItemStateChanged

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        if (consultando) {
            resetarTela();
        } else {
            if (validarCampos()) { //corrigir de acordo com o gui escala
                empresa = (Empresa) cboEmpresa.getSelectedItem();
                equipe = (Equipe) cboEquipe.getSelectedItem();
                DefaultListModel lstn = (DefaultListModel) lstNaoMatriculados.getModel();
                DefaultListModel lstm = (DefaultListModel) lstMatriculados.getModel();
                
                prepararConsulta();
                
                try {
                    alunos = dadosAluno.getList();
                } catch (Exception e) {
                }
                
                for (Aluno al : alunos) {
                    if (al.getEstadoAluno().equals(EstadoAluno.MATRICULADO)) {
                        lstm.addElement(al);
                    }
                }
                
                if (chbTodasEmpresas.isSelected()) {
                    for (Aluno al : alunos) {
                        if (al.getEstadoAluno().equals(EstadoAluno.NAO_MATRICULADO)) {
                            lstn.addElement(al);
                        }
                    }
                } else {
                    for (Aluno al : alunos) {
                        if (al.getEstadoAluno().equals(EstadoAluno.NAO_MATRICULADO)&&(al.getEmpresaColaborador().equals(empresa))) {
                            lstn.addElement(al);
                        }
                    }
                }

                lblEquipeSelecionada.setText(equipe.getDescricaoEquipe());
                atualizarTotalizadores();
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void pnlAlunoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlAlunoComponentShown
        // TODO add your handling code here:


    }//GEN-LAST:event_pnlAlunoComponentShown

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        DefaultListModel lstNaoMat = (DefaultListModel) lstNaoMatriculados.getModel();
        DefaultListModel lstMat = (DefaultListModel) lstMatriculados.getModel();
        Equipe eq = (Equipe) cboEquipe.getSelectedItem();
        
        for (int i=0; i<lstNaoMat.getSize(); i++) {
            Aluno al = (Aluno) lstNaoMat.getElementAt(i);
            al.desmatricularAluno();
        }

        for (int i=0; i<lstMat.getSize(); i++) {
            Aluno al = (Aluno) lstMat.getElementAt(i);
            al.matricularAluno(eq);
        }

        try {
            dadosAluno.alterar();
            JOptionPane.showMessageDialog(null, "Associações realizadas com sucesso!", "Associação de Colaborador", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Associação de Colaborador", JOptionPane.ERROR_MESSAGE);
        }
        
        resetarTela();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAssociarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarTodosActionPerformed
        // TODO add your handling code here:
        DefaultListModel lstNaoMat = (DefaultListModel) lstNaoMatriculados.getModel();
        DefaultListModel lstMat = (DefaultListModel) lstMatriculados.getModel();
        
        for (int i=0; i<lstNaoMat.getSize(); i++) {
            Aluno al = (Aluno) lstNaoMat.getElementAt(i);
            lstMat.addElement(al);
        }
        
        lstNaoMat.removeAllElements();
        atualizarTotalizadores();
    }//GEN-LAST:event_btnAssociarTodosActionPerformed

    private void chbTodasEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTodasEmpresasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chbTodasEmpresasActionPerformed

    private void btnDesassociarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesassociarTodosActionPerformed
        // TODO add your handling code here:
        DefaultListModel lstNaoMat = (DefaultListModel) lstNaoMatriculados.getModel();
        DefaultListModel lstMat = (DefaultListModel) lstMatriculados.getModel();

        for (int i=0; i<lstMat.getSize(); i++) {
            Aluno al = (Aluno) lstMat.getElementAt(i);
            lstNaoMat.addElement(al);
        }
        
        lstMat.removeAllElements();
        
        atualizarTotalizadores();
    }//GEN-LAST:event_btnDesassociarTodosActionPerformed

    private void btnAssociarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarUmActionPerformed
        // TODO add your handling code here:
        if (!lstNaoMatriculados.isSelectionEmpty()) {
            DefaultListModel lstNaoMat = (DefaultListModel) lstNaoMatriculados.getModel();
            DefaultListModel lstMat = (DefaultListModel) lstMatriculados.getModel();

            Aluno al = (Aluno) lstNaoMat.get(lstNaoMatriculados.getSelectedIndex());
            lstMat.addElement(al);
            lstNaoMat.removeElement(al);

            atualizarTotalizadores();
        }

    }//GEN-LAST:event_btnAssociarUmActionPerformed

    private void btnDesassociarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesassociarUmActionPerformed
        // TODO add your handling code here:
        if (!lstMatriculados.isSelectionEmpty()) {
            DefaultListModel lstNaoMat = (DefaultListModel) lstNaoMatriculados.getModel();
            DefaultListModel lstMat = (DefaultListModel) lstMatriculados.getModel();

            Aluno al = (Aluno) lstMat.get(lstMatriculados.getSelectedIndex());
            lstNaoMat.addElement(al);
            lstMat.removeElement(al);

            atualizarTotalizadores();
        }

    }//GEN-LAST:event_btnDesassociarUmActionPerformed

    public void resetarTela() {
        DefaultListModel lstNaoMat = (DefaultListModel) lstNaoMatriculados.getModel();
        DefaultListModel lstMat = (DefaultListModel) lstMatriculados.getModel();
        lstMat.removeAllElements();
        lstNaoMat.removeAllElements();
        
        
        consultando = false;
        lblEquipeSelecionada.setText("");
        lblTotalNaoMatriculados.setText("0");
        lblTotalMatriculados.setText("0");
        btnConsultar.setText("Consultar");
        btnGravar.setEnabled(false);
        cboEmpresa.setEnabled(true);
        cboEquipe.setEnabled(true);
        lstNaoMatriculados.setEnabled(false);
        lstMatriculados.setEnabled(false);
        chbTodasEmpresas.setEnabled(true);
        chbTodasEmpresas.setSelected(false);
        btnAssociarTodos.setEnabled(false);
        btnAssociarUm.setEnabled(false);
        btnDesassociarTodos.setEnabled(false);
        btnDesassociarUm.setEnabled(false);
        btnGravar.setEnabled(false);
        
        totalMatriculados = 0;
        totalNaoMatriculados = 0;
    }
    
    public void prepararConsulta() {
        DefaultListModel lstn = (DefaultListModel) lstNaoMatriculados.getModel();
        DefaultListModel lstm = (DefaultListModel) lstMatriculados.getModel();
        lstn.removeAllElements();
        lstm.removeAllElements();
        
        consultando = true;
        btnConsultar.setText("Cancelar");
        btnGravar.setEnabled(true);
        cboEmpresa.setEnabled(false);
        cboEquipe.setEnabled(false);
        lstNaoMatriculados.setEnabled(true);
        lstMatriculados.setEnabled(true);
        chbTodasEmpresas.setEnabled(false);
        btnAssociarTodos.setEnabled(true);
        btnAssociarUm.setEnabled(true);
        btnDesassociarTodos.setEnabled(true);
        btnDesassociarUm.setEnabled(true);

    }
    
    public void preencherCboEmpresa() {
        cboEmpresa.removeAllItems();
        cboEmpresa.addItem(cboInicialFiltrar);

        try {
            empresas = dadosEmpresa.getList();
        } catch (Exception e) {
            
        }
        for (Empresa emp: empresas) {
            cboEmpresa.addItem(emp);
        }
        
    }
    
    public void preencherCboEquipe(Empresa empresa) {
        cboEquipe.removeAllItems();
        cboEquipe.addItem(cboInicialSelecionar);

        try {
            equipes = dadosEquipe.getList();
        } catch (Exception e) {
            
        }
        
        for (Equipe eq : equipes) {
            if (eq.getEmpresa().equals(empresa)) cboEquipe.addItem(eq);
        }
    }
    
    public void atualizarTotalizadores() {
        DefaultListModel lstn = (DefaultListModel) lstNaoMatriculados.getModel();
        DefaultListModel lstm = (DefaultListModel) lstMatriculados.getModel();
        
        lblTotalNaoMatriculados.setText(Integer.toString(lstn.getSize()));
        lblTotalMatriculados.setText(Integer.toString(lstm.getSize()));
    }
    
    public boolean validarCampos() {
        if (cboEquipe.getSelectedItem()==cboInicialSelecionar) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma equipe.", "Associação de Colaborador", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssociarTodos;
    private javax.swing.JButton btnAssociarUm;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDesassociarTodos;
    private javax.swing.JButton btnDesassociarUm;
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<Object> cboEmpresa;
    private javax.swing.JComboBox<Object> cboEquipe;
    private javax.swing.JCheckBox chbTodasEmpresas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEmpresaAluno;
    private javax.swing.JLabel lblEquipe;
    private javax.swing.JLabel lblEquipeSelecionada;
    private javax.swing.JLabel lblTimeAluno;
    private javax.swing.JLabel lblTotalMatriculados;
    private javax.swing.JLabel lblTotalNaoMatriculados;
    private javax.swing.JList<Object> lstMatriculados;
    private javax.swing.JList<Object> lstNaoMatriculados;
    private javax.swing.JPanel pnlAluno;
    private javax.swing.JPanel pnlDados1;
    // End of variables declaration//GEN-END:variables
}
