/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DadosContextoInfracao;
import dao.DadosTipoInfracao;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.ContextoInfracao;
import model.TipoInfracao;

/**
 *
 * @author Ygor
 */
public class GuiCadInfracao extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiTurma
     */
    public GuiCadInfracao() {
        initComponents();
    }
    
    public static GuiCadInfracao getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiCadInfracao();
    }
    
    private static boolean aberto = false;
    private boolean alterando = false;
    private final DadosContextoInfracao dadosContextosInfracao = new DadosContextoInfracao();
    private final DadosTipoInfracao dadosTipoInfracao = new DadosTipoInfracao();
    private final String cboInicialSelecionar = "Selecione";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tpnlInfracoes = new javax.swing.JTabbedPane();
        pnlContexto = new javax.swing.JPanel();
        lblEmpresa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContextoInfracao = new javax.swing.JTable();
        btnCadastrarContextoInfracao = new javax.swing.JButton();
        lblEmpresa1 = new javax.swing.JLabel();
        txtDescricaoContexto = new javax.swing.JTextField();
        txtPontuacaoContexto = new javax.swing.JTextField();
        pnlTipoInfracao = new javax.swing.JPanel();
        lblEmpresa2 = new javax.swing.JLabel();
        btnCadastrarTipoInfracao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTipoInfracao = new javax.swing.JTable();
        lblEmpresa3 = new javax.swing.JLabel();
        cboContexoInfracao = new javax.swing.JComboBox<>();
        txtDescricaoInfracao = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JToggleButton();
        btnRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cadastro de Infrações");

        tpnlInfracoes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tpnlInfracoesComponentShown(evt);
            }
        });

        pnlContexto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlContextoComponentShown(evt);
            }
        });

        lblEmpresa.setText("Descrição do Contexto:");

        tblContextoInfracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Contexto", "Pontuação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContextoInfracao);
        if (tblContextoInfracao.getColumnModel().getColumnCount() > 0) {
            tblContextoInfracao.getColumnModel().getColumn(1).setMinWidth(100);
            tblContextoInfracao.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblContextoInfracao.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        btnCadastrarContextoInfracao.setText("Gravar");
        btnCadastrarContextoInfracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarContextoInfracaoActionPerformed(evt);
            }
        });

        lblEmpresa1.setText("Pontuação:");

        txtDescricaoContexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoContextoActionPerformed(evt);
            }
        });

        txtPontuacaoContexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontuacaoContextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContextoLayout = new javax.swing.GroupLayout(pnlContexto);
        pnlContexto.setLayout(pnlContextoLayout);
        pnlContextoLayout.setHorizontalGroup(
            pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlContextoLayout.createSequentialGroup()
                        .addGroup(pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpresa)
                            .addComponent(txtDescricaoContexto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContextoLayout.createSequentialGroup()
                                .addComponent(txtPontuacaoContexto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrarContextoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEmpresa1))
                        .addContainerGap(77, Short.MAX_VALUE))))
        );
        pnlContextoLayout.setVerticalGroup(
            pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPontuacaoContexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarContextoInfracao)
                    .addComponent(txtDescricaoContexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tpnlInfracoes.addTab("Contexto", pnlContexto);

        pnlTipoInfracao.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlTipoInfracaoComponentShown(evt);
            }
        });

        lblEmpresa2.setText("Descrição da Infração:");

        btnCadastrarTipoInfracao.setText("Gravar");
        btnCadastrarTipoInfracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarTipoInfracaoActionPerformed(evt);
            }
        });

        tblTipoInfracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Descrição", "Contexto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTipoInfracao);

        lblEmpresa3.setText("Contexto equivalente:");

        txtDescricaoInfracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoInfracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTipoInfracaoLayout = new javax.swing.GroupLayout(pnlTipoInfracao);
        pnlTipoInfracao.setLayout(pnlTipoInfracaoLayout);
        pnlTipoInfracaoLayout.setHorizontalGroup(
            pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoInfracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlTipoInfracaoLayout.createSequentialGroup()
                        .addGroup(pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpresa3)
                            .addComponent(cboContexoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpresa2)
                            .addGroup(pnlTipoInfracaoLayout.createSequentialGroup()
                                .addComponent(txtDescricaoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrarTipoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTipoInfracaoLayout.setVerticalGroup(
            pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoInfracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpresa3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTipoInfracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricaoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarTipoInfracao)
                    .addComponent(cboContexoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        tpnlInfracoes.addTab("Tipos de Infração", pnlTipoInfracao);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnRemover.setText("Excluir");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tpnlInfracoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(165, 165, 165)
                                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tpnlInfracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btnVoltar)
                    .addComponent(btnAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int opcao
        = JOptionPane.showOptionDialog(null,
            "Confirma a exclusão?",
            "Pergunta",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null,
            new String[]{"Sim", "Não"}, "Sim");
        
        if (opcao == 0) {            
            if (pnlContexto.isShowing()) {
                ContextoInfracao contextoInfracao = (ContextoInfracao) tblContextoInfracao.getValueAt(tblContextoInfracao.getSelectedRow(), 0);
                try {
                    dadosContextosInfracao.remover(contextoInfracao);
                } catch (Exception headlessException) {
                    JOptionPane.showMessageDialog(rootPane, "Contexto removido com sucesso.");
                }

                preencherTabelaContextoInfracao();
                
            } if (pnlTipoInfracao.isShowing()){
                TipoInfracao tipoInfracao = (TipoInfracao) tblTipoInfracao.getValueAt(tblTipoInfracao.getSelectedRow(), 0);
                try {
                    dadosTipoInfracao.remover(tipoInfracao);
                } catch (Exception headlessException) {
                    JOptionPane.showMessageDialog(rootPane, "Tipo de Infração removido com sucesso.");
                }
                preencherTabelaTipoInfracao();
            }
        }
        

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        preencherTabelaContextoInfracao();
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if (alterando) {
            resetarTelaContextoInfracao();
            resetarTelaTipoInfracao();
        }
 
        else {
            if (pnlContexto.isShowing()) {
                try {
                    ContextoInfracao contextoInfracao = (ContextoInfracao) tblContextoInfracao.getValueAt(tblContextoInfracao.getSelectedRow(), 0);
                    txtDescricaoContexto.setText(contextoInfracao.getDescricao());
                    txtPontuacaoContexto.setText(contextoInfracao.getPontuacao().toString());
                    txtDescricaoContexto.requestFocus();
                    txtDescricaoContexto.selectAll();
                    alterando = true;
                    btnAlterar.setText("Alterando");
                    btnAlterar.setSelected(true);
                    tblContextoInfracao.setEnabled(false);
                    tpnlInfracoes.setEnabled(false);
                } catch (Exception headlessException) {
                    JOptionPane.showMessageDialog(null, "Selecione um Contexto de Infração", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
                    btnAlterar.setSelected(false);
                }
            } if (pnlTipoInfracao.isShowing()) {
                try {
                    TipoInfracao tipoInfracao = (TipoInfracao) tblTipoInfracao.getValueAt(tblTipoInfracao.getSelectedRow(), 0);
                    cboContexoInfracao.setSelectedItem((ContextoInfracao) tipoInfracao.getContextoTipoInfracao());
                    txtDescricaoInfracao.setText(tipoInfracao.getDescricaoTipoInfracao());
                    txtDescricaoInfracao.requestFocus();
                    txtDescricaoInfracao.selectAll();
                    alterando = true;
                    btnAlterar.setText("Alterando");
                    btnAlterar.setSelected(true);
                    tblTipoInfracao.setEnabled(false);
                    tpnlInfracoes.setEnabled(false);
                } catch (Exception headlessException) {
                    JOptionPane.showMessageDialog(null, "Selecione um Tipo de Infração.", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
                    btnAlterar.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarContextoInfracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarContextoInfracaoActionPerformed
        // TODO add your handling code here:
        if (validarCamposContexto()) {
            if (!alterando) {
                String descricaoContexto = txtDescricaoContexto.getText();
                Integer pontuacaoContexto = Integer.parseInt(txtPontuacaoContexto.getText());
                ContextoInfracao contextoInfracao = new ContextoInfracao(descricaoContexto, pontuacaoContexto);
                try {
                    dadosContextosInfracao.incluir(contextoInfracao);
                    JOptionPane.showMessageDialog(null, "Contexto cadastrado com sucesso!", "Cadastro de Infração", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                ContextoInfracao contextoInfracao = (ContextoInfracao) tblContextoInfracao.getValueAt(tblContextoInfracao.getSelectedRow(), 0);
                contextoInfracao.setDescricao(txtDescricaoContexto.getText());
                contextoInfracao.setPontuacao(Integer.parseInt(txtPontuacaoContexto.getText()));
                try {
                    dadosContextosInfracao.alterar();
                    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "Cadastro de Infração", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
                }
            }

            preencherTabelaContextoInfracao();
        }
    }//GEN-LAST:event_btnCadastrarContextoInfracaoActionPerformed

    private void txtDescricaoContextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoContextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoContextoActionPerformed

    private void txtPontuacaoContextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontuacaoContextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontuacaoContextoActionPerformed

    private void txtDescricaoInfracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoInfracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoInfracaoActionPerformed

    private void btnCadastrarTipoInfracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarTipoInfracaoActionPerformed
        // TODO add your handling code here:
        if (validarCamposTiposInfracao()) {
            if (!alterando) {
                ContextoInfracao contextoInfracao = (ContextoInfracao) cboContexoInfracao.getSelectedItem();
                String descricaoInfracao = txtDescricaoInfracao.getText();
                TipoInfracao tipoInfracao = new TipoInfracao(descricaoInfracao, contextoInfracao);
                try {
                    dadosTipoInfracao.incluir(tipoInfracao);
                    JOptionPane.showMessageDialog(null, "Tipo de Infracao cadastrado com sucesso!", "Cadastro de Infração", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                TipoInfracao tipoInfracao = (TipoInfracao) tblTipoInfracao.getValueAt(tblTipoInfracao.getSelectedRow(), 1);
                tipoInfracao.setDescricaoTipoInfracao(txtDescricaoInfracao.getText());
                try {
                    dadosContextosInfracao.alterar();
                    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "Cadastro de Infração", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
                }
            }

            preencherTabelaTipoInfracao();
        }
    }//GEN-LAST:event_btnCadastrarTipoInfracaoActionPerformed

    private void tpnlInfracoesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tpnlInfracoesComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_tpnlInfracoesComponentShown

    private void pnlContextoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlContextoComponentShown
        // TODO add your handling code here:
        preencherTabelaContextoInfracao();
    }//GEN-LAST:event_pnlContextoComponentShown

    private void pnlTipoInfracaoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlTipoInfracaoComponentShown
        // TODO add your handling code here:
        cboContexoInfracao.removeAllItems();
        
        cboContexoInfracao.addItem(cboInicialSelecionar);
        List<ContextoInfracao> contextosInfracao = new ArrayList<>();
        try {
            contextosInfracao = new DadosContextoInfracao().getList();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nenhum Contexto de Infração encontrado!", "Cadastro de Infrações", JOptionPane.ERROR_MESSAGE);
        }
        for (ContextoInfracao contextoInfracao : contextosInfracao) {
            cboContexoInfracao.addItem(contextoInfracao);
        }
        
        preencherTabelaTipoInfracao();

    }//GEN-LAST:event_pnlTipoInfracaoComponentShown
    
    public void preencherTabelaContextoInfracao() {
        DefaultTableModel tbl = (DefaultTableModel) tblContextoInfracao.getModel();
        tblContextoInfracao.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }

        List<ContextoInfracao> contextosInfracao = new ArrayList();
        try {
           contextosInfracao = dadosContextosInfracao.getList();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nenhum contexto encontrado!", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
        }
        
        for (int i = 0; i < contextosInfracao.size(); i++) {
            ContextoInfracao contexto = (ContextoInfracao) contextosInfracao.get(i);
            Object linha [] = {contexto, contexto.getPontuacao()};
            tbl.addRow(linha);
        }

        resetarTelaContextoInfracao();
    }
    
    public void preencherTabelaTipoInfracao() {
        DefaultTableModel tbl = (DefaultTableModel) tblTipoInfracao.getModel();
        tblTipoInfracao.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        List<TipoInfracao> tiposInfracao = new ArrayList<>();
        try {
            tiposInfracao = dadosTipoInfracao.getList();
        } catch (Exception ex) {
            Logger.getLogger(GuiCadInfracao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0; i < tiposInfracao.size(); i++) {
            TipoInfracao tipoInfracao = (TipoInfracao) tiposInfracao.get(i);
            Object linha [] = {tipoInfracao, tipoInfracao.getContextoTipoInfracao().getDescricao()};
            tbl.addRow(linha);
        }

        resetarTelaTipoInfracao();
    }
    
    public void resetarTelaContextoInfracao() {
        txtDescricaoContexto.setText("");
        txtDescricaoContexto.requestFocus();
        btnAlterar.setEnabled(true);
        btnAlterar.setSelected(false);
        btnAlterar.setText("Alterar");
        tpnlInfracoes.setEnabled(true);
        tblContextoInfracao.setEnabled(true);
        
    }
    
    public void resetarTelaTipoInfracao() {
        cboContexoInfracao.setSelectedIndex(0);
        txtDescricaoInfracao.setText("");
        txtDescricaoInfracao.requestFocus();
        btnAlterar.setEnabled(true);
        btnAlterar.setSelected(false);
        btnAlterar.setText("Alterar");
        tpnlInfracoes.setEnabled(true);
        tblTipoInfracao.setEnabled(true);

    }
    
    public boolean validarCamposContexto() {
        if(!(txtDescricaoContexto.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a Descrição do Contexto de Infração.", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
            txtDescricaoContexto.requestFocus();
            return false;
        }
        
        if(!(txtPontuacaoContexto.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a Pontuação do Contexto de Infração.", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
            txtDescricaoContexto.requestFocus();
            return false;
        }
        
        return true;
    }
    
    public boolean validarCamposTiposInfracao() {
        if ((cboContexoInfracao.getSelectedItem().equals(cboInicialSelecionar))) {
            JOptionPane.showMessageDialog(null, "Selecione um Contexto de Infração.", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
            cboContexoInfracao.showPopup();
            return false;
        }
        
        if (!(txtDescricaoInfracao.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a Descrição da Infração.", "Cadastro de Infração", JOptionPane.ERROR_MESSAGE);
            txtDescricaoContexto.requestFocus();
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JButton btnCadastrarContextoInfracao;
    private javax.swing.JButton btnCadastrarTipoInfracao;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Object> cboContexoInfracao;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEmpresa1;
    private javax.swing.JLabel lblEmpresa2;
    private javax.swing.JLabel lblEmpresa3;
    private javax.swing.JPanel pnlContexto;
    private javax.swing.JPanel pnlTipoInfracao;
    private javax.swing.JTable tblContextoInfracao;
    private javax.swing.JTable tblTipoInfracao;
    private javax.swing.JTabbedPane tpnlInfracoes;
    private javax.swing.JTextField txtDescricaoContexto;
    private javax.swing.JTextField txtDescricaoInfracao;
    private javax.swing.JTextField txtPontuacaoContexto;
    // End of variables declaration//GEN-END:variables
}
