/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DadosFuncao;
import dao.DadosTipoPercurso;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Funcao;
import model.TipoPercurso;

/**
 *
 * @author Ygor
 */
public class GuiCadPercurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiEmpresa
     */
    public GuiCadPercurso() {
        initComponents();
    }
    
    public static GuiCadPercurso getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiCadPercurso();
    }
    
    private static boolean aberto = false;
    private boolean alterando = false;
    private TipoPercurso tipoPercurso;
    private final DadosTipoPercurso dadosTipoPercurso = new DadosTipoPercurso();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPercursos = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JToggleButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cadastro de Percursos");

        lblFuncao.setText("Descrição do Percurso:");

        tblPercursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPercursos);
        if (tblPercursos.getColumnModel().getColumnCount() > 0) {
            tblPercursos.getColumnModel().getColumn(0).setMinWidth(30);
            tblPercursos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblPercursos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btnCadastrar.setText("Gravar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnRemover.setText("Excluir");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFuncao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(lblFuncao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btnVoltar)
                    .addComponent(btnAlterar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if (validarCampos()) {
            if (!alterando) {
                String descricaoPercurso = txtDescricao.getText();
                tipoPercurso = new TipoPercurso (descricaoPercurso);
                try {
                    dadosTipoPercurso.incluir(tipoPercurso);
                    JOptionPane.showMessageDialog(null, "Percurso cadastrado com sucesso!", "Cadastro de Percurso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Percurso", JOptionPane.ERROR_MESSAGE);
                }
                
            } else {
                tipoPercurso = (TipoPercurso) tblPercursos.getValueAt(tblPercursos.getSelectedRow(), 0);
                tipoPercurso.setDescricao(txtDescricao.getText());
                try {
                    dadosTipoPercurso.alterar();
                    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "Cadastro de Percurso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Percurso", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            preencherTabela();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int opcao
        = JOptionPane.showOptionDialog(null,
            "Confirma a exclusão?",
            "Pergunta",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null,
            new String[]{"Sim", "Não"}, "Sim");
        if (opcao == 0) {
            this.tipoPercurso = (TipoPercurso) tblPercursos.getValueAt(tblPercursos.getSelectedRow(), 0);
            try {
                dadosTipoPercurso.remover(this.tipoPercurso);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            JOptionPane.showMessageDialog(rootPane, "Percurso removido com sucesso.");
            
            preencherTabela();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        preencherTabela();
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if (alterando) resetarTela();
        else {
            try {
                tipoPercurso = (TipoPercurso) tblPercursos.getValueAt(tblPercursos.getSelectedRow(), 0);
                String descricao = tipoPercurso.getDescricao();
                txtDescricao.setText(descricao);
                txtDescricao.requestFocus();
                txtDescricao.selectAll();
                alterando = true;
                btnAlterar.setText("Alterando");
                btnAlterar.setSelected(true);
                tblPercursos.setEnabled(false);
            } catch (Exception headlessException) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um percurso.");
                btnAlterar.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed
    
    public void preencherTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblPercursos.getModel();
        tblPercursos.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }

        List<TipoPercurso> tiposPercurso = new ArrayList();
        try {
           tiposPercurso = dadosTipoPercurso.getList();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nenhum percurso encontrado!", "Cadastro de Percurso", JOptionPane.ERROR_MESSAGE);
        }
        
        for (int i = 0; i < tiposPercurso.size(); i++) {
            TipoPercurso tipoPercurso = (TipoPercurso) tiposPercurso.get(i);
            Object linha [] = {tipoPercurso, tipoPercurso.getDescricao()};
            tbl.addRow(linha);
        }

        resetarTela();
    }
    
    public void resetarTela() {
        txtDescricao.setText("");
        txtDescricao.requestFocus();
        btnAlterar.setEnabled(true);
        btnAlterar.setSelected(false);
        btnAlterar.setText("Alterar");
        tblPercursos.setEnabled(true);
    }
    
    public boolean validarCampos() {
        if(!(txtDescricao.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a Descrição do Percurso.");
            txtDescricao.requestFocus();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JTable tblPercursos;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
