/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import restrincoes.RstNumeros;
import dao.DadosAluno;
import dao.DadosEmpresa;
import dao.DadosFuncao;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Aluno;
import model.Empresa;
import model.EstadoColaborador;
import model.Funcao;

/**
 *
 * @author Ygor
 */
public class GuiCadAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiColaborador
     */
    public GuiCadAluno() {
        initComponents();
        txtMatricula.setDocument(new RstNumeros());
        
    }
    public static GuiCadAluno getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiCadAluno();
    }
    
    private static boolean aberto = false;
    private boolean alterando = false;
    private boolean cadastrando = false;
    private boolean consultando = true;
    private Aluno aluno;
    private final DadosAluno dadosAluno = new DadosAluno();
    private final DadosEmpresa dadosEmpresa = new DadosEmpresa();
    private final DadosFuncao dadosFuncao = new DadosFuncao();
    private List<Empresa> empresas = new ArrayList<>();
    private List<Funcao> funcoes = new ArrayList();
    private static final String cboInicial = "Selecione: ";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlDados = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        lblNome1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        cboEmpresa = new javax.swing.JComboBox<Object>();
        cboFuncao = new javax.swing.JComboBox<Object>();
        lblFuncao = new javax.swing.JLabel();
        rbtnDesligado = new javax.swing.JRadioButton();
        rbtnAfastado = new javax.swing.JRadioButton();
        rbtnAtivo = new javax.swing.JRadioButton();
        lblEmpresa2 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblColaboradores = new javax.swing.JTable();
        btnAlterar = new javax.swing.JToggleButton();
        btnRemoverColaborador = new javax.swing.JButton();
        btnRemoverColaborador1 = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cadastro de Usuários");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBorder(null);
        setClosable(true);
        setTitle("Cadastro de Alunos - Controle de Treinamentos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlDados.setBackground(new java.awt.Color(187, 199, 255));
        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtMatricula.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyTyped(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGravar.setText("Consultar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lblNome1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome1.setText("Matrícula:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmpresa.setText("Empresa:");

        cboEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cboEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEmpresaItemStateChanged(evt);
            }
        });

        cboFuncao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cboFuncao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFuncaoItemStateChanged(evt);
            }
        });

        lblFuncao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFuncao.setText("Função:");

        rbtnDesligado.setBackground(new java.awt.Color(187, 199, 255));
        buttonGroup1.add(rbtnDesligado);
        rbtnDesligado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbtnDesligado.setText("Desligado");

        rbtnAfastado.setBackground(new java.awt.Color(187, 199, 255));
        buttonGroup1.add(rbtnAfastado);
        rbtnAfastado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbtnAfastado.setText("Afastado");

        rbtnAtivo.setBackground(new java.awt.Color(187, 199, 255));
        buttonGroup1.add(rbtnAtivo);
        rbtnAtivo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbtnAtivo.setText("Ativo");

        lblEmpresa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmpresa2.setText("Situação:");

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome1)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpresa))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(cboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFuncao)))
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addComponent(lblEmpresa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAfastado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnDesligado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addComponent(lblNome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                                .addComponent(lblEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                                .addComponent(lblFuncao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmpresa2)
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnAtivo)
                            .addComponent(rbtnAfastado)
                            .addComponent(rbtnDesligado))))
                .addContainerGap())
        );

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("+ Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 64));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Alunos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(187, 199, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblColaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Aluno", "Empresa", "Função", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblColaboradores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblColaboradoresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblColaboradoresFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(tblColaboradores);
        if (tblColaboradores.getColumnModel().getColumnCount() > 0) {
            tblColaboradores.getColumnModel().getColumn(0).setPreferredWidth(250);
            tblColaboradores.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblColaboradores.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblColaboradores.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        btnAlterar.setBackground(new java.awt.Color(187, 191, 255));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnRemoverColaborador.setBackground(new java.awt.Color(187, 191, 255));
        btnRemoverColaborador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoverColaborador.setText("Excluir");
        btnRemoverColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverColaboradorActionPerformed(evt);
            }
        });

        btnRemoverColaborador1.setBackground(new java.awt.Color(187, 191, 255));
        btnRemoverColaborador1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoverColaborador1.setText("Mais Detalhes");
        btnRemoverColaborador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverColaborador1ActionPerformed(evt);
            }
        });

        btnVoltar1.setBackground(new java.awt.Color(187, 191, 255));
        btnVoltar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoverColaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverColaborador)
                    .addComponent(btnVoltar1)
                    .addComponent(btnAlterar)
                    .addComponent(btnRemoverColaborador1))
                .addContainerGap())
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JCA_Small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Cadastro de Alunos");
        getAccessibleContext().setAccessibleDescription("Cadastro de Alunos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        if (consultando) {
            if(!(txtMatricula.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a matrícula do colaborador.", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            txtMatricula.requestFocus();
            } else {
                Integer matriculaConsulta = Integer.parseInt(txtMatricula.getText());
                preencherTabelaMatricula(matriculaConsulta);
            }
            
        } else if (validarCampos()) {
            Empresa empresa = (Empresa) cboEmpresa.getSelectedItem();
            Funcao funcao = (Funcao) cboFuncao.getSelectedItem();
            Integer matricula = Integer.parseInt(txtMatricula.getText());
            String nome = txtNome.getText();
            String estado = new String();
            if (rbtnAtivo.isSelected()) estado = EstadoColaborador.ATIVO.toString();
            else if (rbtnAfastado.isSelected()) estado = EstadoColaborador.AFASTADO.toString();
            else if (rbtnDesligado.isSelected()) estado = EstadoColaborador.DESLIGADO.toString();
            
            if (cadastrando) {
                Aluno al = new Aluno (empresa, funcao, matricula, nome, EstadoColaborador.valueOf(estado));
                try {
                    dadosAluno.incluir(al);
                    JOptionPane.showMessageDialog(null, "Colaborador cadastrado com sucesso!", "Cadastro de Colaborador", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
                }
                

            int opcao
                = JOptionPane.showOptionDialog(null,
                    "Continuar Cadastrando?",
                    "Pergunta",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null,
                    new String[]{"Sim", "Não"}, "Sim");
            if (opcao == 1) {
                preencherTabela();
            } else if (opcao == 0) {
                preencherTabela();
                btnCadastrar.doClick();
                consultando = false;
                alterando = false;
                cadastrando = true;
                cboEmpresa.setSelectedItem(empresa);
                cboFuncao.setSelectedItem(funcao);
                txtMatricula.requestFocus();
                
            }

            } else if (alterando) {
                Aluno al = (Aluno) tblColaboradores.getValueAt(tblColaboradores.getSelectedRow(), 0);
                al.setEmpresaColaborador(empresa);
                al.setFuncaoColaborador(funcao);
                al.setMatricula(matricula);
                al.setNome(nome);
                al.setEstadoColaborador(EstadoColaborador.valueOf(estado));

                try {
                    dadosAluno.alterar();
                    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "Cadastro de Colaborador", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
                }
                preencherTabela();
            }      
            
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        cboEmpresa.removeAllItems();
        cboEmpresa.addItem(cboInicial);
        try {
            empresas = new DadosEmpresa().getList();
        } catch (Exception ex) {
            Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Empresa empresa: empresas) {
           cboEmpresa.addItem(empresa);
        }
           
        cboFuncao.removeAllItems();
        cboFuncao.addItem(cboInicial);
        try {
            funcoes = new DadosFuncao().getList();
        } catch (Exception ex) {
            Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Funcao funcao: funcoes) {
            cboFuncao.addItem(funcao);
        }
        
        preencherTabela();
        resetarCbo();
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyTyped
        // TODO add your handling code here:
        int quantidadeCaracteres = 6;
        if (txtMatricula.getText().length() >= quantidadeCaracteres) {
            String textoProcessado = txtMatricula.getText();
            char ch = textoProcessado.charAt(textoProcessado.length()-1);
            textoProcessado = textoProcessado.replace(String.valueOf(ch), "");
            txtMatricula.setText(textoProcessado);
            //CharSequence subSequence = txtMatricula.getText().subSequence(0, quantidadeCaracteres-1);
            //txtMatricula.setText((String) subSequence);
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_txtMatriculaKeyTyped

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if (cadastrando) {
            resetarTela();
            preencherTabela();
        }
        else {
            txtMatricula.requestFocus();
            txtNome.setEnabled(true);
            pnlDados.setEnabled(true);
            btnCadastrar.setText("Cadastrando");
            btnCadastrar.setSelected(true);
            btnGravar.setText("Gravar");
            btnAlterar.setEnabled(false);
            btnRemoverColaborador.setEnabled(false);
            btnRemoverColaborador1.setEnabled(false);
            cadastrando = true;
            consultando = false;
            alterando = false;
            cboEmpresa.setEnabled(true);
            cboFuncao.setEnabled(true);
            cboEmpresa.setSelectedIndex(0);
            cboFuncao.setSelectedIndex(0);
            rbtnAtivo.setEnabled(true);
            rbtnAfastado.setEnabled(true);
            rbtnDesligado.setEnabled(true);

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tblColaboradoresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblColaboradoresFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblColaboradoresFocusGained

    private void tblColaboradoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblColaboradoresFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblColaboradoresFocusLost

    private void cboEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEmpresaItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cboEmpresaItemStateChanged

    private void cboFuncaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFuncaoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cboFuncaoItemStateChanged

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        preencherTabela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMatriculaKeyPressed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnRemoverColaborador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverColaborador1ActionPerformed
        // TODO add your handling code here:
        if (alterando) resetarTela();
        else {
            try {
                aluno = (Aluno) tblColaboradores.getValueAt(tblColaboradores.getSelectedRow(), 0);
                GuiRelAluno g = GuiRelAluno.getInstance();
                g.setAluno(aluno);
                g.setVisible(true);
            } catch (Exception headlessException) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um colaborador.");
                btnAlterar.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnRemoverColaborador1ActionPerformed

    private void btnRemoverColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverColaboradorActionPerformed
        // TODO add your handling code here:
        try {
            Aluno al = (Aluno) tblColaboradores.getValueAt(tblColaboradores.getSelectedRow(), 0);

            int opcao
            = JOptionPane.showOptionDialog(null,
                "Confirma a exclusão?",
                "Pergunta",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null,
                new String[]{"Sim", "Não"}, "Sim");

            if (opcao == 0) {
                dadosAluno.remover(al);
                JOptionPane.showMessageDialog(rootPane, "Colaborador removido com sucesso.");
            }

            preencherTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um colaborador.");
        }
    }//GEN-LAST:event_btnRemoverColaboradorActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if (alterando || cadastrando) resetarTela();
        else {
            try {
                aluno = (Aluno) tblColaboradores.getValueAt(tblColaboradores.getSelectedRow(), 0);
                cboEmpresa.getModel().setSelectedItem(aluno.getEmpresaColaborador());
                cboFuncao.getModel().setSelectedItem(aluno.getFuncaoColaborador());
                txtMatricula.setText(aluno.getMatricula().toString());
                txtMatricula.setEnabled(false);
                txtNome.setText(aluno.getNome());
                txtNome.requestFocus();
                txtNome.selectAll();
                btnAlterar.setSelected(true);
                btnAlterar.setText("Alterando");
                btnGravar.setText("Consultar");
                btnCadastrar.setEnabled(false);
                btnGravar.setText("Gravar");
                btnRemoverColaborador.setEnabled(false);
                btnRemoverColaborador1.setEnabled(false);
                alterando = true;
                consultando = false;
                cadastrando = false;
                tblColaboradores.setEnabled(false);
                cboEmpresa.setEnabled(true);
                cboFuncao.setEnabled(true);
                txtNome.setEnabled(true);
                rbtnAtivo.setEnabled(true);
                rbtnAfastado.setEnabled(true);
                rbtnDesligado.setEnabled(true);
                if (null == aluno.getEstadoColaborador()) alterando = true;
                else switch (aluno.getEstadoColaborador()) {
                    case ATIVO:
                    rbtnAtivo.setSelected(true);
                    break;
                    case AFASTADO:
                    rbtnAfastado.setSelected(true);
                    break;
                    case DESLIGADO:
                    rbtnDesligado.setSelected(true);
                    default:
                    alterando = true;
                    break;
                }

            } catch (Exception headlessException) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um colaborador.");
                btnAlterar.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    public void preencherTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblColaboradores.getModel();
        tblColaboradores.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        List<Aluno> alunos = new ArrayList<>();
        try {
            alunos = dadosAluno.getList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
        }

        for (Aluno al : alunos) {
            Object linha [] = {al, al.getEmpresaColaborador().getNomeEmpresa(), al.getFuncaoColaborador().getDescricaoFuncao(), al.getEstadoColaborador()};
            tbl.addRow(linha);
        }
        
        resetarTela();
    }
    
    public void preencherTabelaEmpresa(Empresa empresa) {
        DefaultTableModel tbl = (DefaultTableModel) tblColaboradores.getModel();
        tblColaboradores.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        List<Aluno> alunos = new ArrayList<>();
        try {
            alunos = dadosAluno.getList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
        }
        
        for (Aluno al : alunos) {
            if (al.getEmpresaColaborador().equals(empresa)) {
                Object linha [] = {al, al.getNome(), al.getEmpresaColaborador().getNomeEmpresa(), al.getFuncaoColaborador().getDescricaoFuncao(), al.getEstadoColaborador()};
                tbl.addRow(linha);
            }
        }

        if (tbl.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            preencherTabela();
        } else resetarTela();
    }
    
    public void preencherTabelaFuncao(Funcao funcao) {
        DefaultTableModel tbl = (DefaultTableModel) tblColaboradores.getModel();
        tblColaboradores.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        List<Aluno> alunos = new ArrayList<>();
        try {
            alunos = dadosAluno.getList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
        }

        for (Aluno al : alunos) {
            if (al.getFuncaoColaborador().equals(funcao)) {
                Object linha [] = {al, al.getNome(), al.getEmpresaColaborador().getNomeEmpresa(), al.getFuncaoColaborador().getDescricaoFuncao(), al.getEstadoColaborador()};
                tbl.addRow(linha);
            }
        }
        
        if (tbl.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
        } else resetarTela();
    }
    
    public void preencherTabelaMatricula(Integer matricula) {
        DefaultTableModel tbl = (DefaultTableModel) tblColaboradores.getModel();
        tblColaboradores.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        List<Aluno> alunos = new ArrayList<>();
        try {
            alunos = dadosAluno.getList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
        }

        for (Aluno al : alunos) {
            if (al.getMatricula().equals(matricula)) {
            Object linha [] = {al, al.getNome(), al.getEmpresaColaborador().getNomeEmpresa(), al.getFuncaoColaborador().getDescricaoFuncao(), al.getEstadoColaborador()};
                tbl.addRow(linha);
            }
        }
        
        if (tbl.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum colaborador encontrado!", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            preencherTabela();
        } else resetarTela();
    }
    
    public void resetarCbo() {
        cboEmpresa.setSelectedIndex(0);
        cboFuncao.setSelectedIndex(0);
        cboEmpresa.setEnabled(false);
        cboFuncao.setEnabled(false);
    }
    
    public void resetarTela() {
        txtMatricula.setText("");
        txtNome.setText("");
        txtNome.setEnabled(false);
        txtMatricula.setEnabled(true);
        txtMatricula.requestFocus();
        rbtnAtivo.setSelected(true);
        rbtnAfastado.setSelected(false);
        rbtnDesligado.setSelected(false);
        btnAlterar.setEnabled(true);
        btnAlterar.setSelected(false);
        btnAlterar.setText("Alterar");
        btnCadastrar.setSelected(false);
        btnCadastrar.setText("+ Cadastrar");
        btnCadastrar.setEnabled(true);
        btnGravar.setText("Consultar");
        btnRemoverColaborador.setEnabled(true);
        btnRemoverColaborador1.setEnabled(true);
        rbtnAtivo.setEnabled(false);
        rbtnAfastado.setEnabled(false);
        rbtnDesligado.setEnabled(false);
        tblColaboradores.setEnabled(true);
        pnlDados.setEnabled(false);
        alterando = false;
        cadastrando = false;
        consultando = true;
        resetarCbo();
    }
    
    public boolean validarCampos() {
        if(cboEmpresa.getSelectedItem().equals(cboInicial)) {
            JOptionPane.showMessageDialog(null, "Selecione uma empresa", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            cboEmpresa.showPopup();
            return false;
        }
        
        if(cboFuncao.getSelectedItem().equals(cboInicial)) {
            JOptionPane.showMessageDialog(null, "Selecione uma função", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            cboFuncao.showPopup();
            return false;
        }
        
        if(!(txtMatricula.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a matrícula do colaborador.", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            txtMatricula.requestFocus();
            return false;
        }
        
        if(!(txtNome.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe o nome do colaborador.", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
            return false;
        }
        
        if(!(rbtnAtivo.isSelected() || rbtnAfastado.isSelected() || rbtnDesligado.isSelected())){
            JOptionPane.showMessageDialog(null, "Selecione uma Situação.", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        List<Aluno> alunos = new ArrayList<>();
        for (Aluno al : alunos) {
            if (txtMatricula.getText().equals(al.getMatricula().toString())) {
                JOptionPane.showMessageDialog(null, "O colaborador " + al.getNome() + " já se encontra cadastrado.", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
                txtMatricula.requestFocus();
                return false;
            }
        }
        return true;
    }

    public boolean validarCampoMatricula() {
        if(!(txtMatricula.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a matrícula do colaborador.", "Cadastro de Colaborador", JOptionPane.ERROR_MESSAGE);
            txtMatricula.requestFocus();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JToggleButton btnCadastrar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemoverColaborador;
    private javax.swing.JButton btnRemoverColaborador1;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<Object> cboEmpresa;
    private javax.swing.JComboBox<Object> cboFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEmpresa2;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JRadioButton rbtnAfastado;
    private javax.swing.JRadioButton rbtnAtivo;
    private javax.swing.JRadioButton rbtnDesligado;
    private javax.swing.JTable tblColaboradores;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
