/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DadosAluno;
import dao.DadosAulaEscalada;
import dao.DadosAulaFrequentada;
import dao.DadosInstrutor;
import dao.DadosEmpresa;
import dao.DadosEquipe;
import dao.DadosTipoPercurso;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Aluno;
import model.AulaEscalada;
import model.AulaMinistrada;
import model.Empresa;
import model.Equipe;
import model.EstadoAluno;
import model.EstadoAulaEscalada;
import model.InfracaoCometida;
import model.Instrutor;
import model.TipoPercurso;

/**
 *
 * @author Ygor
 */
public class GuiFrequencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiTurma
     */
    public GuiFrequencia() {
        initComponents();
    }
    
    public static GuiFrequencia getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiFrequencia();
    }
    
    private static boolean aberto = false;
    private boolean alterando = false;
    private boolean registrando = false;
    private boolean consultando = false;
    private static String cboInicialFiltrar = "Filtrar:";
    private static String cboInicialSelecionar = "Selecionar:";
    
    private DadosEmpresa dadosEmpresa = new DadosEmpresa();
    private DadosEquipe dadosEquipe = new DadosEquipe();
    private DadosAulaEscalada dadosAulaEscalada = new DadosAulaEscalada();
    private DadosAulaFrequentada dadosAulaFrequentada = new DadosAulaFrequentada();
    private DadosInstrutor dadosInstrutor = new DadosInstrutor();
    private DadosAluno dadosAluno = new DadosAluno();
    private final DadosTipoPercurso dadosTipoPercurso = new DadosTipoPercurso();
    
    private List<Empresa> empresas = new ArrayList<>();
    private List<Equipe> equipes = new ArrayList<>();
    private List<AulaEscalada> aulasEscaladas = new ArrayList<>();
    private List<AulaMinistrada> aulasMinistradas = new ArrayList<>();
    private List<Instrutor> instrutores = new ArrayList<>();
    private List<Aluno> alunos = new ArrayList<>();
    private List<TipoPercurso> tiposPercurso = new ArrayList<>();
    
    private Empresa empresa;
    private Equipe equipe;
    private AulaEscalada aulaEscalada;
    private AulaMinistrada aulaMinistrada;
    private Instrutor instrutor;
    private TipoPercurso tipoPercurso;
    private Aluno aluno;
    private String numeroCarro;
    
    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public AulaEscalada getAulaEscalada() {
        return aulaEscalada;
    }

    public void setAulaEscalada(AulaEscalada aulaEscalada) {
        this.aulaEscalada = aulaEscalada;
    }

    public AulaMinistrada getAulaFrequentada() {
        return aulaMinistrada;
    }

    public void setAulaFrequentada(AulaMinistrada aulaFrequentada) {
        this.aulaMinistrada = aulaFrequentada;
    }

    public Instrutor getInstrutor() {
        return instrutor;
    }

    public void setInstrutor(Instrutor instrutor) {
        this.instrutor = instrutor;
    }

    public TipoPercurso getTipoPercurso() {
        return tipoPercurso;
    }

    public void setTipoPercurso(TipoPercurso tipoPercurso) {
        this.tipoPercurso = tipoPercurso;
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public String getNumeroCarro() {
        return numeroCarro;
    }

    public void setNumeroCarro(String numeroCarro) {
        this.numeroCarro = numeroCarro;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAlterar = new javax.swing.JToggleButton();
        btnGravar = new javax.swing.JButton();
        btnRegistrarPenalidades = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEmpresa2 = new javax.swing.JLabel();
        rbtnAndamento = new javax.swing.JRadioButton();
        rbtnRealizada = new javax.swing.JRadioButton();
        chbTodosAula = new javax.swing.JCheckBox();
        cboEquipe = new javax.swing.JComboBox<>();
        cboAulaEscalada = new javax.swing.JComboBox<>();
        lblEmpresa8 = new javax.swing.JLabel();
        lblEmpresa5 = new javax.swing.JLabel();
        cboEmpresa = new javax.swing.JComboBox<>();
        lblEmpresa7 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEmpresa10 = new javax.swing.JLabel();
        cboInstrutor = new javax.swing.JComboBox<>();
        chbTodosInstrutor = new javax.swing.JCheckBox();
        cboPercurso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroCarro = new javax.swing.JTextField();
        lblEmpresa11 = new javax.swing.JLabel();
        btnDefinir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFrequencias = new javax.swing.JTable();

        setClosable(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnRegistrarPenalidades.setText("Registrar Penalidades | Parecer");
        btnRegistrarPenalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPenalidadesActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados da Escala"));

        lblEmpresa2.setText("Situação:");

        buttonGroup1.add(rbtnAndamento);
        rbtnAndamento.setText("Em Andamento");

        buttonGroup1.add(rbtnRealizada);
        rbtnRealizada.setText("Realizada");

        chbTodosAula.setText("Exibir todos");
        chbTodosAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTodosAulaActionPerformed(evt);
            }
        });

        cboEquipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar..." }));
        cboEquipe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEquipeItemStateChanged(evt);
            }
        });

        cboAulaEscalada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cboAulaEscalada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAulaEscaladaItemStateChanged(evt);
            }
        });

        lblEmpresa8.setText("Aula Escalada:");

        lblEmpresa5.setText("Empresa:");

        cboEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar..." }));
        cboEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEmpresaItemStateChanged(evt);
            }
        });

        lblEmpresa7.setText("Equipe:");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpresa5)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpresa7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmpresa8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chbTodosAula))
                            .addComponent(cboAulaEscalada, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmpresa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAndamento)
                        .addGap(10, 10, 10)
                        .addComponent(rbtnRealizada)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa5)
                    .addComponent(lblEmpresa7)
                    .addComponent(lblEmpresa8)
                    .addComponent(chbTodosAula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAulaEscalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnAndamento)
                        .addComponent(rbtnRealizada)
                        .addComponent(lblEmpresa2))
                    .addComponent(btnConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpar.setText("Limpar / Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jButton1.setText("+ Registrar");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Controle de Frequência");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Percurso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblEmpresa10.setText("Instrutor:");

        cboInstrutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        chbTodosInstrutor.setText("Exibir todos");
        chbTodosInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTodosInstrutorActionPerformed(evt);
            }
        });

        cboPercurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cboPercurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPercursoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Percurso:");

        lblEmpresa11.setText("Número do Carro:");

        btnDefinir.setText("Definir");
        btnDefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEmpresa10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbTodosInstrutor))
                    .addComponent(cboInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cboPercurso, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumeroCarro)
                    .addComponent(lblEmpresa11))
                .addGap(18, 18, 18)
                .addComponent(btnDefinir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa10)
                    .addComponent(chbTodosInstrutor)
                    .addComponent(jLabel1)
                    .addComponent(lblEmpresa11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPercurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefinir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblFrequencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Aluno", "Qtde Infra.", "Pontuação", "Presença", "Parecer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFrequencias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFrequencias.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblFrequencias);
        if (tblFrequencias.getColumnModel().getColumnCount() > 0) {
            tblFrequencias.getColumnModel().getColumn(1).setMinWidth(80);
            tblFrequencias.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblFrequencias.getColumnModel().getColumn(1).setMaxWidth(80);
            tblFrequencias.getColumnModel().getColumn(2).setMinWidth(80);
            tblFrequencias.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblFrequencias.getColumnModel().getColumn(2).setMaxWidth(80);
            tblFrequencias.getColumnModel().getColumn(3).setMinWidth(80);
            tblFrequencias.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblFrequencias.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarPenalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(btnLimpar))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnRegistrarPenalidades)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);

    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        try {
            this.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        
        }
        
        if (!registrando) {
            prepararConsulta();

            cboEmpresa.removeAllItems();
            cboEmpresa.addItem(cboInicialSelecionar);
            try {
                empresas = new DadosEmpresa().getList();
            } catch (Exception e) {

            }
            for (Empresa emp: empresas) {
                cboEmpresa.addItem(emp);
            }

            cboPercurso.removeAllItems();
            cboPercurso.addItem(cboInicialSelecionar);
            try {
                tiposPercurso = dadosTipoPercurso.getList();
            } catch (Exception ex) {
                Logger.getLogger(GuiFrequencia.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (TipoPercurso percurso : tiposPercurso) {
                cboPercurso.addItem(percurso);
            }

            resetarTela();
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        /*
        if (alterando) resetarTela();
        else {
            try {
                funcao = (Funcao) tblTurma.getValueAt(tblTurma.getSelectedRow(), 0);
                String descricaoFuncao = funcao.getDescricao();
                txtTurma.setText(descricaoFuncao);
                txtTurma.requestFocus();
                txtTurma.selectAll();
                alterando = true;
                btnAlterar.setText("Alterando");
                btnAlterar.setSelected(true);
                tblTurma.setEnabled(false);
            } catch (Exception headlessException) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione uma função.");
                btnAlterar.setSelected(false);
            }
        }
        */
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        int opcao
        = JOptionPane.showOptionDialog(null,
            "Esta aula se encontra em " + EstadoAulaEscalada.ANDAMENTO +
                    "\n Confirma a conclusão do relatório desta aula?",
            "Pergunta",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null,
            new String[]{"Sim", "Não."}, "Sim");

        if (opcao == 0) {
            
            aulaEscalada = (AulaEscalada) cboAulaEscalada.getSelectedItem();
            
            // Verre a tabela
            int qtdLinhas = tblFrequencias.getRowCount();
            for (int i = qtdLinhas - 1; i >= 0; i--) {
                aluno = (Aluno) tblFrequencias.getValueAt(i, 0);

                // Verifica qual aula está sendo tratada
                for (AulaMinistrada aula : aluno.getAulasMinistradas()) {
                    if (aula.getAulaEscalada().equals(aulaEscalada)) {
                        aulaMinistrada = aula;
                        break;
                    }
                }
                
                // Define a presença/falta
                Boolean presenca = (Boolean) tblFrequencias.getValueAt(i, 3);
                if (presenca.equals(true)) {
                    aulaMinistrada.setPresenca(true);
                } else {
                    aulaMinistrada.setPresenca(false);
                }
            }
            
            aulaEscalada.concluirAula();

            try {
                dadosAluno.alterar();
                dadosAulaEscalada.alterar();
                JOptionPane.showMessageDialog(null, "Aula concluída com sucesso!", "Gestão de Frequência", JOptionPane.INFORMATION_MESSAGE);
                resetarTela();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não foi possível concluir esta operação.", "Gestão de Frequência", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void cboEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEmpresaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED && cboEmpresa.getSelectedItem()!=cboInicialSelecionar) { // Restringe execução apenas em caso de seleção manual no combobox
            Empresa emp = (Empresa) cboEmpresa.getSelectedItem();
            
            cboEquipe.removeAllItems();
            cboEquipe.addItem(cboInicialFiltrar);
            try {
                equipes = dadosEquipe.getList();
            } catch (Exception e) {

            }
            for (Equipe equi : equipes) {
                if (equi.getEmpresa().equals(emp)) {
                    cboEquipe.addItem(equi);
                }
            }
            
            cboInstrutor.removeAllItems();
            cboInstrutor.addItem(cboInicialSelecionar);
            try {
                instrutores = dadosInstrutor.getList();
            } catch (Exception e) {

            }
            for (Instrutor inst : instrutores) {
                cboInstrutor.addItem(inst);
            }
            
        }
    }//GEN-LAST:event_cboEmpresaItemStateChanged

    private void cboEquipeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEquipeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED && cboEquipe.getSelectedItem()!=cboInicialFiltrar) { // Restringe execução apenas em caso de seleção manual no combobox
            Empresa emp = (Empresa) cboEmpresa.getSelectedItem();

            try {
                aulasEscaladas = dadosAulaEscalada.getList();
            } catch (Exception e) {
            
            }   
                    
            cboAulaEscalada.removeAllItems();
            cboAulaEscalada.addItem(cboInicialSelecionar);
            for (AulaEscalada aula : aulasEscaladas) {
                if (aula.getEstadoAulaEscalada().equals(EstadoAulaEscalada.ANDAMENTO) && aula.getEquipe().getEmpresa().equals(emp)) {
                    cboAulaEscalada.addItem(aula);
                }
            }
        }
    }//GEN-LAST:event_cboEquipeItemStateChanged

    private void cboAulaEscaladaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAulaEscaladaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange()==ItemEvent.SELECTED && cboAulaEscalada.getSelectedItem()!=cboInicialSelecionar) { // Restringe execução apenas em caso de seleção manual no combobox
            aulaEscalada = (AulaEscalada) cboAulaEscalada.getSelectedItem();
            if(aulaEscalada.getEstadoAulaEscalada().equals(EstadoAulaEscalada.ANDAMENTO)) rbtnAndamento.setSelected(true);
            if(aulaEscalada.getEstadoAulaEscalada().equals(EstadoAulaEscalada.CONCLUIDO)) rbtnRealizada.setSelected(true);
        }
        btnConsultar.requestFocus();
    }//GEN-LAST:event_cboAulaEscaladaItemStateChanged

    private void btnRegistrarPenalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPenalidadesActionPerformed
        // TODO add your handling code here:
        try {
            aluno = (Aluno) tblFrequencias.getValueAt(tblFrequencias.getSelectedRow(), 0);
            
            // Marca presença para aluno a receber penalidades, caso esteja desmarcado.
            if (tblFrequencias.getValueAt(tblFrequencias.getSelectedRow(), 3).equals(false)) {
                tblFrequencias.setValueAt(true, tblFrequencias.getSelectedRow(), 3);
            }
        
            // Verifica qual aula frequentada está sendo tratada
            for (AulaMinistrada aula : aluno.getAulasMinistradas()) {
                if (aula.getAulaEscalada().equals(aulaEscalada)) {
                    aulaMinistrada = aula;
                    break;
                }
            }

            GuiRegPenalidade gp = GuiRegPenalidade.getInstance();
            gp.setAluno(aluno);
            gp.setAulaFrequentada(aulaMinistrada);
            gp.setVisible(true);
            
            try {
                this.setSelected(false);
            } catch (java.beans.PropertyVetoException e) {
                    
            }

            

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um aluno na lista.", "Registro de Penalidade", JOptionPane.ERROR_MESSAGE);
        }


        //preencherTabela();
    }//GEN-LAST:event_btnRegistrarPenalidadesActionPerformed

    private void chbTodosInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTodosInstrutorActionPerformed
        // TODO add your handling code here:
        if (chbTodosInstrutor.isSelected()) {
            cboInstrutor.removeAllItems();
            cboInstrutor.addItem(cboInicialSelecionar);
            try {
                instrutores = dadosInstrutor.getList();
            } catch (Exception e) {

            }
            for (Instrutor inst : instrutores) {
                cboInstrutor.addItem(inst);
            }
            
        } else if (cboEmpresa.getSelectedItem()!=cboInicialSelecionar){
            Empresa emp = (Empresa) cboEmpresa.getSelectedItem();
            cboInstrutor.removeAllItems();
            cboInstrutor.addItem(cboInicialSelecionar);
            try {
                instrutores = dadosInstrutor.getList();
            } catch (Exception e) {

            }
            for (Instrutor inst : instrutores) {
                if (inst.getEmpresaColaborador().equals(emp)) {
                    cboInstrutor.addItem(inst);
                }
            }
            
        } else if(cboEmpresa.getSelectedItem()==cboInicialSelecionar) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma empresa.");
            
        }
    }//GEN-LAST:event_chbTodosInstrutorActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        // consultando = true;
        if (consultando && validarCamposConsulta()){
            aulaEscalada = (AulaEscalada) cboAulaEscalada.getSelectedItem();
            
            if (aulaEscalada.getEstadoAulaEscalada().equals(EstadoAulaEscalada.ANDAMENTO)) {
                int opcao
                = JOptionPane.showOptionDialog(null,
                    "Esta aula se encontra em " + EstadoAulaEscalada.ANDAMENTO +
                            "\n Deseja registrar o relatório desta aula?",
                    "Pergunta",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null,
                    new String[]{"Sim", "Não, apenas desejo consultar."}, "Sim");

                if (opcao == 0) {
                    prepararRelatorio();
                } else {
                    prepararConsulta();
                }
            }
            
            preencherTabelaConsulta();

        } else {
            aulaEscalada = (AulaEscalada) cboAulaEscalada.getSelectedItem();
            prepararRelatorio();
            preencherTabelaRegistro();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        resetarTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void chbTodosAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTodosAulaActionPerformed
        // TODO add your handling code here:
        
        try {
            aulasEscaladas = dadosAulaEscalada.getList();
        } catch (Exception e) {
            
        }
        
        if (chbTodosAula.isSelected() && cboEquipe.getSelectedItem()!=cboInicialSelecionar) {
            equipe = (Equipe) cboEquipe.getSelectedItem();
            cboAulaEscalada.removeAllItems();
            cboAulaEscalada.addItem(cboInicialSelecionar);
            
            for (AulaEscalada aula : aulasEscaladas) {
                if (aula.getEquipe().equals(equipe)) {
                    cboAulaEscalada.addItem(aula);   
                }
            }
            
        }
        
        if (!chbTodosAula.isSelected() && cboEquipe.getSelectedItem()!=cboInicialSelecionar){
            equipe = (Equipe) cboEquipe.getSelectedItem();
            cboAulaEscalada.removeAllItems();
            cboAulaEscalada.addItem(cboInicialSelecionar);
            
            
            for (AulaEscalada aula : aulasEscaladas) {
                if (aula.getEquipe().equals(equipe) && aula.getEstadoAulaEscalada().equals(EstadoAulaEscalada.ANDAMENTO))
                    cboAulaEscalada.addItem(aula);
            }
            
        }
        
        if (cboEquipe.getSelectedItem()==cboInicialSelecionar){
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma equipe.");
        }
    }//GEN-LAST:event_chbTodosAulaActionPerformed

    private void btnDefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirActionPerformed
        // TODO add your handling code here:
        if (validarCamposDefinir()) {
            prepararDefinicao();
            
            aulaEscalada = (AulaEscalada) cboAulaEscalada.getSelectedItem();
            instrutor = (Instrutor) cboInstrutor.getSelectedItem();
            tipoPercurso = (TipoPercurso) cboPercurso.getSelectedItem();
            numeroCarro = txtNumeroCarro.getText();
            
            // Atribui falso para as linhas da tabela
            int qtdLinhass = tblFrequencias.getRowCount();
            for (int i = qtdLinhass - 1; i >= 0; i--) {
                tblFrequencias.setValueAt(false, i, 3);
            }
            
            int qtdLinhas = tblFrequencias.getRowCount();
            for (int i = qtdLinhas - 1; i >= 0; i--) {
                aluno = (Aluno) tblFrequencias.getValueAt(i, 0);
                aluno.inserirAulaMinistradas(aulaEscalada, instrutor, tipoPercurso, numeroCarro, false);
            }
        }
    }//GEN-LAST:event_btnDefinirActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_formFocusGained

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void cboPercursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPercursoItemStateChanged
        // TODO add your handling code here:
    if (evt.getStateChange()==ItemEvent.SELECTED && cboPercurso.getSelectedItem()!=cboInicialSelecionar) { // Restringe execução apenas em caso de seleção manual no combobox {
        txtNumeroCarro.requestFocus();
    }
    }//GEN-LAST:event_cboPercursoItemStateChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentShown

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseWheelMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameIconified

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        if (registrando) 
            //preencherTabelaRegistro();
            atualizarTabela();
    }//GEN-LAST:event_formPropertyChange
    public void preencherTabelaConsulta() {
        DefaultTableModel tbl = (DefaultTableModel) tblFrequencias.getModel();
        //tblFrequencias.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }

        try {
           alunos = new DadosAluno().getList();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nenhum aluno encontrado!", "Frequência", JOptionPane.ERROR_MESSAGE);
        }
            
        equipe = (Equipe) cboEquipe.getSelectedItem();
        for (Aluno al : alunos) {
            if (al.getEstadoAluno().equals(EstadoAluno.MATRICULADO) && al.getEquipeAluno().equals(equipe)) {
                Object linha [] = {al, "-", "-", false, "-"};
                tbl.addRow(linha);
            }
        }
        
    }
   
    public void preencherTabelaRegistro() {
        DefaultTableModel tbl = (DefaultTableModel) tblFrequencias.getModel();
        //tblFrequencias.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        equipe = (Equipe) cboEquipe.getSelectedItem();
        
        // Percorre todos os alunos que estão matriculados na equipe selecionada
        for (Aluno al : alunos) {
            if (al.getEstadoAluno().equals(EstadoAluno.MATRICULADO) && al.getEquipeAluno().equals(equipe)) {
                // Verifica qual aula frequentada está sendo tratada na consulta
                for (int i=0; i<al.getAulasMinistradas().size(); i++) {
                    if (al.getAulasMinistradas().get(i).getAulaEscalada().equals(aulaEscalada)) {
                        // Preenche a tabela com os dados da aula de cada aluno
                        Object linha [] = {al,
                            al.getAulasMinistradas().get(i).getQuantidadeInforacoesCometidas(),
                            al.getAulasMinistradas().get(i).getPontuacaoAulaFrequentada(),
                            al.getAulasMinistradas().get(i).isPresenca(),
                            al.getAulasMinistradas().get(i).getDescricaoParecer()};
                        tbl.addRow(linha);
                    }
                }
            }
        }
    }
    
    public void resetarTela() {
        DefaultTableModel tbl = (DefaultTableModel) tblFrequencias.getModel();
        int qtdLinhas = tbl.getRowCount();
        for (int i = qtdLinhas -1; i>= 0; i--) {
            tbl.removeRow(0);
        }
        consultando = true;
        alterando = false;
        registrando = false;
        cboEmpresa.setEnabled(true);
        cboEmpresa.setSelectedIndex(0);
        cboEquipe.setEnabled(true);
        cboEquipe.setSelectedIndex(0);
        cboAulaEscalada.setEnabled(true);
        cboAulaEscalada.setSelectedIndex(0);
        cboInstrutor.setEnabled(false);
        cboInstrutor.setSelectedIndex(0);
        chbTodosInstrutor.setEnabled(false);
        cboPercurso.setEnabled(false);
        txtNumeroCarro.setEnabled(false);
        txtNumeroCarro.setText("");
        btnGravar.setEnabled(false);
        btnDefinir.setEnabled(false);
        btnRegistrarPenalidades.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnConsultar.setEnabled(true);
        tblFrequencias.setEnabled(false);
        rbtnAndamento.setEnabled(false);
        rbtnRealizada.setEnabled(false);
        chbTodosAula.setSelected(false);
        chbTodosAula.setEnabled(true);
        chbTodosInstrutor.setSelected(false);
        chbTodosAula.setEnabled(true);
    }
    
    private void prepararConsulta() {
        consultando = true;
        registrando = false;
        alterando = false;
        btnConsultar.setEnabled(true);
        tblFrequencias.setEnabled(true);
        chbTodosInstrutor.setEnabled(false);
        cboInstrutor.setEnabled(false);
        cboPercurso.setEnabled(false);
        txtNumeroCarro.setEnabled(false);
        btnGravar.setEnabled(false);
        btnRegistrarPenalidades.setEnabled(false);
        btnAlterar.setEnabled(false);
    }
    
    private void prepararRelatorio() {
        registrando = true;
        consultando = false;
        alterando = false;
        cboEmpresa.setEnabled(false);
        cboEquipe.setEnabled(false);
        cboAulaEscalada.setEnabled(false);
        chbTodosAula.setEnabled(false);
        btnConsultar.setEnabled(false);
        chbTodosInstrutor.setEnabled(true);
        cboInstrutor.setEnabled(true);
        cboInstrutor.requestFocus();
        cboPercurso.setEnabled(true);
        txtNumeroCarro.setEnabled(true);
        tblFrequencias.setEnabled(false);
        btnGravar.setEnabled(false);
        btnRegistrarPenalidades.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnDefinir.setEnabled(true);
        
        // aulaMinistrada = new AulaMinistrada(instrutor, tipoPercurso, ERROR, closable)
    }
    
    private void prepararDefinicao() {
        registrando = true;
        consultando = false;
        alterando = false;
        cboInstrutor.setEnabled(false);
        cboPercurso.setEnabled(false);
        txtNumeroCarro.setEnabled(false);
        tblFrequencias.setEnabled(true);
        btnRegistrarPenalidades.setEnabled(true);
        btnGravar.setEnabled(true);
        btnDefinir.setEnabled(false);
    }
    
    public void atualizarTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblFrequencias.getModel();
        
        int qtdeLinhas = tbl.getRowCount();
        for (int i=qtdeLinhas-1; i>=0; i--) {
            aluno = (Aluno) tblFrequencias.getValueAt(i, 0);
            
            for (AulaMinistrada aula : aluno.getAulasMinistradas()) {
                if (aula.getAulaEscalada().equals(aulaEscalada)) {
                    aulaMinistrada = aula;
                }
            }

            //tbl.setValueAt(aluno, tblFrequencias.getSelectedRow(), 0);
            tbl.setValueAt(aulaMinistrada.getInfracoesCometidas().size(), i, 1);
            tbl.setValueAt(aulaMinistrada.getPontuacaoAulaFrequentada(), i, 2);
            tbl.setValueAt(aulaMinistrada.getPresenca(), i, 3);
            tbl.setValueAt(aulaMinistrada.getDescricaoParecer(), i, 4);
        }
        


    }
    
    public boolean validarCamposDefinir() {
        if (cboInstrutor.getSelectedItem().equals(cboInicialSelecionar)) {
            JOptionPane.showMessageDialog(null, "Selecione um instrutor.");
            cboInstrutor.showPopup();
            return false;
        }
        
        if (cboPercurso.getSelectedItem().equals(cboInicialSelecionar)) {
            JOptionPane.showMessageDialog(null, "Selecione um percurso.");
            cboPercurso.showPopup();
            return false;
        }
        
        if(!(txtNumeroCarro.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe o número do carro.");
            txtNumeroCarro.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private boolean validarCamposConsulta() {
        if(cboEquipe.getSelectedItem().equals(cboInicialFiltrar)) {
            JOptionPane.showMessageDialog(null, "Selecione uma equipe", "Gestão de Frequência", JOptionPane.ERROR_MESSAGE);
            cboEquipe.showPopup();
            return false;
        }
        if(cboAulaEscalada.getSelectedItem().equals(cboInicialSelecionar)) {
            JOptionPane.showMessageDialog(null, "Selecione uma aula escalada", "Gestão de Frequência", JOptionPane.ERROR_MESSAGE);
            cboAulaEscalada.showPopup();
            return false;
        }
        return true;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDefinir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrarPenalidades;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cboAulaEscalada;
    private javax.swing.JComboBox<Object> cboEmpresa;
    private javax.swing.JComboBox<Object> cboEquipe;
    private javax.swing.JComboBox<Object> cboInstrutor;
    private javax.swing.JComboBox<Object> cboPercurso;
    private javax.swing.JCheckBox chbTodosAula;
    private javax.swing.JCheckBox chbTodosInstrutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblEmpresa10;
    private javax.swing.JLabel lblEmpresa11;
    private javax.swing.JLabel lblEmpresa2;
    private javax.swing.JLabel lblEmpresa5;
    private javax.swing.JLabel lblEmpresa7;
    private javax.swing.JLabel lblEmpresa8;
    private javax.swing.JRadioButton rbtnAndamento;
    private javax.swing.JRadioButton rbtnRealizada;
    private javax.swing.JTable tblFrequencias;
    private javax.swing.JTextField txtNumeroCarro;
    // End of variables declaration//GEN-END:variables
}
