package gui;


import dao.DadosLoginParametro;
import dao.DadosUsuario;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LoginParametro;
import model.Usuario;
import model.UsuarioAtual;

/**
 *
 * @author Ygor
 */
public class GuiLogin extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrincipalLogin
     */
    private List<Usuario> usuarios = new ArrayList();
    private LoginParametro parametro;
    private final DadosLoginParametro dadosLoginParametro = new DadosLoginParametro();
    private final DadosUsuario dadosUsuario = new DadosUsuario();
    private static final String cboInicial = "Selecione um Usuário:";
    
    
    public GuiLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGroupRadio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LblUsuario = new javax.swing.JLabel();
        cboUsuario = new javax.swing.JComboBox();
        BtnCadastrarUsuarios = new javax.swing.JButton();
        LblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        BtnEntrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblDiretorioXml = new javax.swing.JTable();
        BtnAlterarDiretorioXml = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        BtnEntrarSemSenha = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Eletrodomésticos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                FormWindowActivate(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                FormWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        LblUsuario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblUsuario.setText("Usuário:");

        cboUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUsuarioItemStateChanged(evt);
            }
        });
        cboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioActionPerformed(evt);
            }
        });

        BtnCadastrarUsuarios.setText("...");
        BtnCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarUsuariosActionPerformed(evt);
            }
        });

        LblSenha.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LblSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblSenha.setText("Senha:");

        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblSenha)
                    .addComponent(LblUsuario))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCadastrarUsuarios)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblUsuario)
                    .addComponent(BtnCadastrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSenha)
                    .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acesso", jPanel1);

        TblDiretorioXml.setBackground(new java.awt.Color(214, 214, 214));
        TblDiretorioXml.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        TblDiretorioXml.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Diretório dos Arquivos XML"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblDiretorioXml.setSelectionBackground(new java.awt.Color(204, 204, 204));
        TblDiretorioXml.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TblDiretorioXml.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TblDiretorioXml);
        if (TblDiretorioXml.getColumnModel().getColumnCount() > 0) {
            TblDiretorioXml.getColumnModel().getColumn(0).setResizable(false);
            TblDiretorioXml.getColumnModel().getColumn(0).setHeaderValue("Diretório dos Arquivos XML");
        }

        jScrollPane3.setViewportView(jScrollPane2);

        BtnAlterarDiretorioXml.setText("Alterar Diretório");
        BtnAlterarDiretorioXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarDiretorioXmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BtnAlterarDiretorioXml)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAlterarDiretorioXml))
        );

        jTabbedPane1.addTab("Configurações", jPanel2);

        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        BtnEntrarSemSenha.setText("Entrar Sem Senha");
        BtnEntrarSemSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarSemSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnEntrarSemSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEntrarSemSenha)
                    .addComponent(BtnSair))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        // TODO add your handling code here:
        if (validaCampos()) {
            
            Usuario usuario = (Usuario) cboUsuario.getSelectedItem();
            String senha = txtSenha.getText();

            if (senha.equals(usuario.getSenha())) {
                UsuarioAtual usuarioAtual = new UsuarioAtual(usuario);
                JOptionPane.showMessageDialog(rootPane, "Bem Vindo, " + usuarioAtual.getNome() + "!");
                
                this.dispose();
                
                GuiPrincipal gp = new GuiPrincipal();
                gp.setVisible(true);
                gp.getLblUsuarioAtual().setText(usuarioAtual.toString());
                gp.getLblNivel().setText(usuarioAtual.getNome().getNivelAcesso());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Senha inválida.");
                txtSenha.setText("");
                txtSenha.requestFocus();
            }
        }

    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSairActionPerformed

    private void FormWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FormWindowOpened
        // TODO add your handling code here:
        preencherTabela();
        txtSenha.requestFocus();
        this.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_FormWindowOpened

    private void BtnAlterarDiretorioXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarDiretorioXmlActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.parametro = (LoginParametro) TblDiretorioXml.getValueAt(TblDiretorioXml.getSelectedRow(), 0);  

            try {
                dadosLoginParametro.remover(this.parametro);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            parametro = new LoginParametro();
            
            parametro.setDiretorioXml(chooser.getSelectedFile().getAbsolutePath());
            
            try {
                dadosLoginParametro.incluir(parametro);
                JOptionPane.showMessageDialog(rootPane, "Diretório Aplicado.");
            } catch (Exception ex) {
                Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 

        preencherTabela();
                
    }//GEN-LAST:event_BtnAlterarDiretorioXmlActionPerformed

    private void BtnCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarUsuariosActionPerformed
        // TODO add your handling code here:
        
        GuiCadUsuario gus = new GuiCadUsuario();
        gus.setVisible(true);

    }//GEN-LAST:event_BtnCadastrarUsuariosActionPerformed

    private void FormWindowActivate(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FormWindowActivate
        // TODO add your handling code here:
        cboUsuario.removeAllItems();
        cboUsuario.addItem(cboInicial);
        try {
            usuarios = new DadosUsuario().getList();
        } catch (Exception ex) {
            Logger.getLogger(GuiLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Usuario usuario : usuarios) {
           cboUsuario.addItem(usuario);
        }
        
        
        preencherTabela();     
        
    }//GEN-LAST:event_FormWindowActivate

    private void cboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuarioActionPerformed

    private void cboUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUsuarioItemStateChanged
        // TODO add your handling code here:
        
        txtSenha.requestFocus();
    }//GEN-LAST:event_cboUsuarioItemStateChanged

    private void BtnEntrarSemSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarSemSenhaActionPerformed
        // TODO add your handling code here:
        this.dispose();

        GuiPrincipal gp = new GuiPrincipal();
        gp.setVisible(true);
    }//GEN-LAST:event_BtnEntrarSemSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiLogin().setVisible(true);
            }
        });
    }
    
    private void preencherTabela() {
        DefaultTableModel tbl = (DefaultTableModel) TblDiretorioXml.getModel();
        int qtdLinhas = tbl.getRowCount();

        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }

        List<LoginParametro> parametros = new ArrayList();
        
        try {
            parametros = dadosLoginParametro.getList();
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex.getMessage());
            //return;
        }

        
        for (int i = 0; i < parametros.size(); i++) {
            LoginParametro parametro = (LoginParametro) parametros.get(i);
            Object linha[] = {parametro};
            tbl.addRow(linha);
        }
        
        TblDiretorioXml.setRowSelectionInterval(0,0); // Seleciona a primeira linha da tabela automaticamente 
    }
    
     public boolean validaCampos() {
        if (!(txtSenha.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Informe a Senha do Usuário.");
            txtSenha.requestFocus();
            return false;
        }
        if (!(cboUsuario.getSelectedItem()!=cboInicial)) {
            JOptionPane.showMessageDialog(null, "Selecione um Usuário.");
            cboUsuario.showPopup();
            return false;
        }
        return true;
    }
    

        
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterarDiretorioXml;
    private javax.swing.JButton BtnCadastrarUsuarios;
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnEntrarSemSenha;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel LblSenha;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JTable TblDiretorioXml;
    private javax.swing.ButtonGroup btnGroupRadio;
    private javax.swing.JComboBox cboUsuario;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
