/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DadosTipoInfracao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Aluno;
import model.AulaMinistrada;
import model.InfracaoCometida;
import model.TipoInfracao;

/**
 *
 * @author Ygor
 */
public class GuiRegPenalidade extends javax.swing.JDialog {

    /**
     * Creates new form GuiRegPenalizacao
     */
    public GuiRegPenalidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static GuiRegPenalidade getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiRegPenalidade(null, true);
    }
    
    private static boolean aberto = false;
    
    private GuiFrequencia guiFrequencia;
    
    private AulaMinistrada aulaMinistrada;
    private Aluno aluno;
    private TipoInfracao tipoInfracao;
    private InfracaoCometida infracaoCometida;
    private String descricaoParecer;

    private List<TipoInfracao> tiposInfracao = new ArrayList<>();

    private final DadosTipoInfracao dadosTipoInfracao = new DadosTipoInfracao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfracoes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        txtParecer = new javax.swing.JTextField();
        lblEmpresa11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblEmpresa = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblFuncao3 = new javax.swing.JLabel();
        lblAluno = new javax.swing.JLabel();
        lblEmpresa1 = new javax.swing.JLabel();
        lblPontuacaoTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Penalidades - Controle de Treinamento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(187, 199, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblInfracoes.setAutoCreateRowSorter(true);
        tblInfracoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Contexto", "Descrição", "Pontos", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblInfracoesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblInfracoes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(187, 199, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnConfirmar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        txtParecer.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        lblEmpresa11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblEmpresa11.setText("Parecer do Instrutor:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEmpresa11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtParecer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpresa11)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(txtParecer))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(187, 199, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEmpresa.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblEmpresa.setText("Data da Aula:");

        lblData.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblData.setText("[DATA DA AULA]");

        lblFuncao3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblFuncao3.setText("Aluno:");

        lblAluno.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblAluno.setText("[NOME DO ALUNO]");

        lblEmpresa1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblEmpresa1.setText("Pontuação Atual:");

        lblPontuacaoTotal.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblPontuacaoTotal.setText("[PONTUAÇÃO]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpresa)
                    .addComponent(lblData))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFuncao3)
                    .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpresa1)
                    .addComponent(lblPontuacaoTotal))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEmpresa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblData))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblFuncao3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblAluno)
                            .addGap(3, 3, 3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmpresa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontuacaoTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JCA_Small.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(0, 0, 64));

        jLabel5.setBackground(new java.awt.Color(51, 51, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro de Penalidades");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        descricaoParecer = txtParecer.getText();
        
        // Limpa as infrações adicionadas nesta aula
        aulaMinistrada.getInfracoesCometidas().clear();
        
        aulaMinistrada.setDescricaoParecer(descricaoParecer);

        // Adiciona as infrações marcadas na tabela para a aula frequentada do aluno em questão.
        int qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            if (tblInfracoes.getValueAt(i, 3).equals(true)) {
                tipoInfracao = (TipoInfracao) tblInfracoes.getValueAt(i, 1);
                aulaMinistrada.inserirInfracao(tipoInfracao);
            } else {
                tipoInfracao = (TipoInfracao) tblInfracoes.getValueAt(i, 1);
                if (aulaMinistrada.getInfracoesCometidas().contains(infracaoCometida))
                    aulaMinistrada.deletarInfracaoCometida(infracaoCometida);
            }
        }
        
        JOptionPane.showMessageDialog(null, "Informações gravadas com sucesso.");
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        
        // Define Labels
        definirData(aulaMinistrada);
        definirAluno(aluno);
        
        preencherTabela();
        txtParecer.setText(aulaMinistrada.getDescricaoParecer());

        definirPontuacaoTotal();
    }//GEN-LAST:event_formWindowOpened

    private void tblInfracoesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfracoesMouseReleased
        // TODO add your handling code here:
        definirPontuacaoTotal();
    }//GEN-LAST:event_tblInfracoesMouseReleased

    /**
     * @param args the command line arguments
     */
   
    public void preencherTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblInfracoes.getModel();
        tblInfracoes.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        try {
            tiposInfracao = dadosTipoInfracao.getList();
        } catch (Exception ex) {
            Logger.getLogger(GuiRegPenalidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Preenche a tabela normalmente;
        for (TipoInfracao infracao : tiposInfracao) {
            Object linha[] = {infracao.getContextoTipoInfracao(), infracao, infracao.getContextoTipoInfracao().getPontuacao(), false};
            tbl.addRow(linha);
        }
        
        // Marca na tabela as infrações selecionadas anteriormente, caso ocorrido.
        qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            for (InfracaoCometida infracao : aulaMinistrada.getInfracoesCometidas()) {
                if (infracao.getTipoInfracao().equals(tipoInfracao)) {
                    infracaoCometida = infracao;
                    break;
                }
            }
            if (aulaMinistrada.getInfracoesCometidas().contains(infracaoCometida))
                tblInfracoes.setValueAt(true, i, 3);
            else 
                tblInfracoes.setValueAt(false, i, 3);
        }
        
        /*
        // Marca na tabela as infrações selecionadas anteriormente, caso ocorrido.
        qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tipoInfracao = (TipoInfracao)tblInfracoes.getValueAt(i, 1);
            // Verifica qual infracao que está sendo tratado no for
            for (InfracaoCometida infracao : aulaMinistrada.getInfracoesCometidas()) {
                if (infracao.getTipoInfracao().equals(tipoInfracao)) {
                    infracaoCometida = infracao;
                }
            }
            if (aulaMinistrada.getInfracoesCometidas().contains(infracaoCometida)) {
                tblInfracoes.setValueAt(true, i, 3);
            }            
        }
        */
        
        /*
        // Marca na tabela as infrações selecionadas anteriormente.
        qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tipoInfracao = (TipoInfracao)tblInfracoes.getValueAt(i, 1);
            for (InfracaoCometida infracaoCometida : aulaMinistrada.getInfracoesCometidas()) {
                if (infracaoCometida.getTipoInfracao().equals(tipoInfracao)) {
                    tblInfracoes.setValueAt(true, i, 3);
                }
            }
        }
        */
        
        definirPontuacaoTotal();
    }

    public void definirData(AulaMinistrada aulaFrequentada) {
        lblData.setText(aulaFrequentada.getAulaEscalada().getDataAulaEscalada().toString());
    }
    
    public void definirAluno(Aluno aluno) {
        lblAluno.setText(aluno.toString());
    }
    
    public void definirPontuacaoTotal() {
        DefaultTableModel tbl = (DefaultTableModel) tblInfracoes.getModel();
        
        int pontuacaoTotal = 0;
        
        int qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas-1; i >= 0; i--) {
            if (tbl.getValueAt(i, 3).equals(Boolean.TRUE)) {
                pontuacaoTotal+=(Integer) tbl.getValueAt(i, 2); // Caso marcado, soma a pontuação da infração a pontuação total
            }
        }
        
        lblPontuacaoTotal.setText(Integer.toString(pontuacaoTotal));
    }

    public GuiFrequencia getGuiFrequencia() {
        return guiFrequencia;
    }

    public void setGuiFrequencia(GuiFrequencia guiFrequencia) {
        this.guiFrequencia = guiFrequencia;
    }

    public AulaMinistrada getAulaFrequentada() {
        return aulaMinistrada;
    }

    public void setAulaFrequentada(AulaMinistrada aulaFrequentada) {
        this.aulaMinistrada = aulaFrequentada;
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public void setTipoInfracao(TipoInfracao tipoInfracao) {
        this.tipoInfracao = tipoInfracao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEmpresa1;
    private javax.swing.JLabel lblEmpresa11;
    private javax.swing.JLabel lblFuncao3;
    private javax.swing.JLabel lblPontuacaoTotal;
    private javax.swing.JTable tblInfracoes;
    private javax.swing.JTextField txtParecer;
    // End of variables declaration//GEN-END:variables
}
