/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DadosTipoInfracao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Aluno;
import model.AulaFrequentada;
import model.InfracaoCometida;
import model.TipoInfracao;

/**
 *
 * @author Ygor
 */
public class GuiRegPenalidade extends javax.swing.JDialog {

    /**
     * Creates new form GuiRegPenalizacao
     */
    public GuiRegPenalidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static GuiRegPenalidade getInstance() {
        if (aberto) return null;
        aberto = true;
        return new GuiRegPenalidade(null, true);
    }
    
    private static boolean aberto = false;
    
    private AulaFrequentada aulaFrequentada;
    private Aluno aluno;
    private TipoInfracao tipoInfracao;
    private InfracaoCometida infracaoCometida;
    private String descricaoParecer;

    private List<TipoInfracao> tiposInfracao = new ArrayList<>();

    private final DadosTipoInfracao dadosTipoInfracao = new DadosTipoInfracao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmpresa1 = new javax.swing.JLabel();
        lblPontuacaoTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblEmpresa = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblFuncao3 = new javax.swing.JLabel();
        lblAluno = new javax.swing.JLabel();
        lblEmpresa11 = new javax.swing.JLabel();
        txtParecer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfracoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblEmpresa1.setText("Pontuação Atual:");

        lblPontuacaoTotal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblPontuacaoTotal.setText("[PONTUAÇÃO]");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrar Infração");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblEmpresa.setText("Data da Aula:");

        lblData.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblData.setText("[DATA DA AULA]");

        lblFuncao3.setText("Aluno:");

        lblAluno.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblAluno.setText("[ALUNO]");

        lblEmpresa11.setText("Parecer do Instrutor:");

        tblInfracoes.setAutoCreateRowSorter(true);
        tblInfracoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Contexto", "Descrição", "Pontos", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblInfracoesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblInfracoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmpresa11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtParecer, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmpresa)
                                        .addComponent(lblData))
                                    .addGap(69, 69, 69)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFuncao3)
                                        .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmpresa1)
                                        .addComponent(lblPontuacaoTotal))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblEmpresa11)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtParecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblEmpresa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmpresa1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPontuacaoTotal))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFuncao3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAluno)))
                            .addGap(19, 19, 19)))
                    .addGap(415, 415, 415)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        descricaoParecer = txtParecer.getText();
        
        // Limpa as infrações adicionadas nesta aula
        aulaFrequentada.getInfracoesCometidas().clear();
        
        aulaFrequentada.setDescricaoParecer(descricaoParecer);

        // Adiciona as infrações marcadas na tabela para a aula frequentada do aluno em questão.
        int qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            if (tblInfracoes.getValueAt(i, 3).equals(true)) {
                tipoInfracao = (TipoInfracao) tblInfracoes.getValueAt(i, 1);
                aulaFrequentada.inserirInfracao(tipoInfracao);
            }
        }
        
        JOptionPane.showMessageDialog(null, "Informações gravadas com sucesso.");
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        aberto = false;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        
        // Define Labels
        definirData(aulaFrequentada);
        definirAluno(aluno);
        
        preencherTabela();
        txtParecer.setText(aulaFrequentada.getDescricaoParecer());

        definirPontuacaoTotal();
    }//GEN-LAST:event_formWindowOpened

    private void tblInfracoesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfracoesMouseReleased
        // TODO add your handling code here:
        definirPontuacaoTotal();
    }//GEN-LAST:event_tblInfracoesMouseReleased

    /**
     * @param args the command line arguments
     */
   
    public void preencherTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblInfracoes.getModel();
        tblInfracoes.setRowSorter(new TableRowSorter(tbl));

        int qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tbl.removeRow(0);
        }
        
        try {
            tiposInfracao = dadosTipoInfracao.getList();
        } catch (Exception ex) {
            Logger.getLogger(GuiRegPenalidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Preenche a tabela normalmente;
        for (TipoInfracao infracao : tiposInfracao) {
            Object linha[] = {infracao.getContextoTipoInfracao(), infracao, infracao.getContextoTipoInfracao().getPontuacao(), false};
            tbl.addRow(linha);
        }
        
        // Marca na tabela as infrações selecionadas anteriormente, caso ocorrido.
        qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tipoInfracao = (TipoInfracao)tblInfracoes.getValueAt(i, 1);
            // Verifica qual infracao que está sendo tratado no for
            for (InfracaoCometida infracao : aulaFrequentada.getInfracoesCometidas()) {
                if (infracao.getTipoInfracao().equals(tipoInfracao)) {
                    infracaoCometida = infracao;
                }
            }
            if (aulaFrequentada.getInfracoesCometidas().contains(infracaoCometida)) {
                tblInfracoes.setValueAt(true, i, 3);
            }            
        }
        
        /*
        // Marca na tabela as infrações selecionadas anteriormente.
        qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tipoInfracao = (TipoInfracao)tblInfracoes.getValueAt(i, 1);
            for (InfracaoCometida infracaoCometida : aulaFrequentada.getInfracoesCometidas()) {
                if (infracaoCometida.getTipoInfracao().equals(tipoInfracao)) {
                    tblInfracoes.setValueAt(true, i, 3);
                }
            }
        }
        */
        
        definirPontuacaoTotal();
    }

    public void definirData(AulaFrequentada aulaFrequentada) {
        lblData.setText(aulaFrequentada.getAulaEscalada().getDataAulaEscalada().toString());
    }
    
    public void definirAluno(Aluno aluno) {
        lblAluno.setText(aluno.toString());
    }
    
    public void definirPontuacaoTotal() {
        DefaultTableModel tbl = (DefaultTableModel) tblInfracoes.getModel();
        
        int pontuacaoTotal = 0;
        
        int qtdLinhas = tblInfracoes.getRowCount();
        for (int i = qtdLinhas-1; i >= 0; i--) {
            if (tbl.getValueAt(i, 3).equals(Boolean.TRUE)) {
                pontuacaoTotal+=(Integer) tbl.getValueAt(i, 2); // Caso marcado, soma a pontuação da infração a pontuação total
            }
        }
        
        lblPontuacaoTotal.setText(Integer.toString(pontuacaoTotal));
    }

    public AulaFrequentada getAulaFrequentada() {
        return aulaFrequentada;
    }

    public void setAulaFrequentada(AulaFrequentada aulaFrequentada) {
        this.aulaFrequentada = aulaFrequentada;
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public void setTipoInfracao(TipoInfracao tipoInfracao) {
        this.tipoInfracao = tipoInfracao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEmpresa1;
    private javax.swing.JLabel lblEmpresa11;
    private javax.swing.JLabel lblFuncao3;
    private javax.swing.JLabel lblPontuacaoTotal;
    private javax.swing.JTable tblInfracoes;
    private javax.swing.JTextField txtParecer;
    // End of variables declaration//GEN-END:variables
}
